apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  schemaVersion: v1.0.0
  name: brtc-swift-sample-application
  description: Sample application that implements the BRTC Swift SDK
  annotations:
    github.com/project-slug: Bandwidth/brtc-swift-sample-application
  organization: BW
  costCenter: 
  platformType: 
  buildPlatform: GitHub Actions
spec:
  type: Service
  owner: github/band-programmable-voice
  lifecycle: Prototype
  
